### ISSUE TITLE
Lift is freezing with Postgres when non standard port is used

### ISSUE THREAD

**Issue by pantharshit00** [prisma/lift#10]
![image](https://user-images.githubusercontent.com/22195362/59611445-a206a600-911b-11e9-81f1-b5bec5db7b27.png)

Backtrace, after waiting a while:
```
Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionError(Error(Some("error connecting to server: Connection refused (os error 61)"))

stack backtrace:
   0: backtrace::backtrace::trace::h862903ac52cf58ce (0x10e5cd8ae)
   1: backtrace::capture::Backtrace::new_unresolved::hb838890310508129 (0x10e5cca78)
   2: failure::backtrace::internal::InternalBacktrace::new::hbdea59428e164bec (0x10e5cc419)
   3: <failure::backtrace::Backtrace as core::default::Default>::default::h9577f3a4e995077c (0x10e5cc605)
   4: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h4d07df56971b73db (0x10e1c772d)
   5: prisma_query::connector::postgres::PostgreSql::new::h413358e50dc533a4 (0x10e1e2fba)
   6: sql_migration_connector::SqlMigrationConnector::postgres_helper::hb687846233117d88 (0x10e1662a0)
   7: sql_migration_connector::SqlMigrationConnector::exists::hcbffc19b3c042435 (0x10e1653ef)
   8: migration_core::connector_loader::load_connector::hcd8a949dd5611bbb (0x10e076249)
   9: migration_core::migration_engine::MigrationEngine::init::h5a6429317c6e4260 (0x10e06b778)
  10: <F as jsonrpc_core::calls::RpcMethodSimple>::call::h6e069197e6f3babd (0x10e0b1ad8)
  11: <F as jsonrpc_core::calls::RpcMethod<T>>::call::h8b6fef1ab8ef20ba (0x10e057b9c)
  12: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h5ef5874cf77881d7 (0x10e06a982)
  13: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::h80fed1dfafe2a57a (0x10e058360)
  14: <futures::future::map::Map<A, F> as futures::future::Future>::poll::he446a6b868c6556a (0x10e073c9f)
  15: <futures::future::either::Either<A, B> as futures::future::Future>::poll::he5d0fb6984529d00 (0x10e06ac10)
  16: futures::task_impl::std::set::h372284ab71bba6f7 (0x10e0a816f)
  17: <std::thread::local::LocalKey<T>>::with::h5153996dbd9d4602 (0x10e0aad16)
  18: futures::future::Future::wait::hff1c28893df49fb7 (0x10e0737ea)
  19: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync::h91d7fd7e20b983ba (0x10e054d3f)
  20: migration_core::rpc_api::RpcApi::handle::h77f23d4b4ddc65ed (0x10e0b717b)
  21: migration_engine::main::h431600cedbc9116a (0x10e02eb3d)
  22: std::rt::lang_start::{{closure}}::h7cf2cabe6e9ed7ab (0x10e02e926)
  23: std::panicking::try::do_call::h20c95c457c762d5f (0x10e5e57d8)
  24: ___rust_maybe_catch_panic (0x10e5e947f)
  25: std::rt::lang_start_internal::he82d111f45e8971a (0x10e5e62be)
  26: _main (0x10e02eb99))', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: sql_migration_connector::SqlMigrationConnector::postgres_helper
  10: sql_migration_connector::SqlMigrationConnector::exists
  11: migration_core::connector_loader::load_connector
  12: migration_core::migration_engine::MigrationEngine::init
  13: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  14: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  15: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
  16: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  17: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A, B> as futures::future::Future>::poll
  19: futures::task_impl::std::set
  20: <std::thread::local::LocalKey<T>>::with
  21: futures::future::Future::wait
  22: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync
  23: migration_core::rpc_api::RpcApi::handle
  24: migration_engine::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: std::rt::lang_start_internal
  29: main
```

**Comment by pantharshit00** [comment]
Same is true for MySQL when I try to run `prisma2 lift up`

```
Datamodel that will initialize the db:

datasource db {
  provider = "mysql"
  url      = "mysql://root:Harshit00@localhost:5432/issue_60"
}

enum Priviliages {
  ADMIN
  USER
}

model User {
  id          String      @id @default(cuid())
  username    String      @unique
  password    String
  age         Int         @default(18)
  priviliages Priviliages
}

Database Changes:

Migration            Database actions           Status

20190628202848-init  1 CreateTable statements.

You can get the detailed db changes with prisma2 lift up --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md
Error: Error in lift engine for rpc applyMigration:
  thread 'main' panicked at 'Connecting to MySQL failed: ConnectionError(Error(Some("DriverError { Could not connect to address `localhost:5432\': Connection refused (os error 61) }"))

stack backtrace:
   0: backtrace::backtrace::trace::h862903ac52cf58ce (0x106f4aa7e)
   1: backtrace::capture::Backtrace::new_unresolved::hb838890310508129 (0x106f49c48)
   2: failure::backtrace::internal::InternalBacktrace::new::hbdea59428e164bec (0x106f495e9)
   3: <failure::backtrace::Backtrace as core::default::Default>::default::h9577f3a4e995077c (0x106f497d5)
   4: prisma_query::connector::mysql::Mysql::new_from_url::hf4590b8974d5da91 (0x106a3cfc1)
   5: sql_migration_connector::SqlMigrationConnector::mysql_helper::h319c71c7919ed40a (0x10699ed95)
   6: sql_migration_connector::SqlMigrationConnector::new::hb98877956af14210 (0x10699d93e)
   7: migration_core::connector_loader::load_connector::h529c0b25a920f1c8 (0x1068dc0f2)
   8: migration_core::migration_engine::MigrationEngine::init::ha45c0a4cfc0cfb7f (0x1068d9fe8)
   9: <F as jsonrpc_core::calls::RpcMethodSimple>::call::hd2624a075befb389 (0x106922ed9)
  10: <F as jsonrpc_core::calls::RpcMethod<T>>::call::hedb19f7be90fdf6e (0x1068c65ac)
  11: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h3b5b85445d8d74a6 (0x1068d91f2)
  12: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::hcf279068325be644 (0x1068c6bb0)
  13: <futures::future::map::Map<A, F> as futures::future::Future>::poll::h0b0e8198a896ad62 (0x1068e234f)
  14: <futures::future::either::Either<A, B> as futures::future::Future>::poll::hc887be37d832628e (0x1068d9480)
  15: futures::task_impl::std::set::ha48ca7ca98878fb4 (0x106916aff)
  16: <std::thread::local::LocalKey<T>>::with::hbf7a040c89d328cc (0x1069196a6)
  17: futures::future::Future::wait::h6c47660a8ddc59a4 (0x1068e1fda)
  18: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync::h94618f706a6d72eb (0x1068c358f)
  19: migration_core::rpc_api::RpcApi::handle::h347c3a0308f3fa33 (0x106925b0b)
  20: migration_engine::main::h56cf3725d9ba3fee (0x10689d38d)
  21: std::rt::lang_start::{{closure}}::hb4827f207a9be37a (0x10689d336)
  22: std::panicking::try::do_call::h20c95c457c762d5f (0x106f63c28)
  23: ___rust_maybe_catch_panic (0x106f684bf)
  24: std::rt::lang_start_internal::he82d111f45e8971a (0x106f6470e)
  25: _main (0x10689d3e9))', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: sql_migration_connector::SqlMigrationConnector::mysql_helper
  10: sql_migration_connector::SqlMigrationConnector::new
  11: migration_core::connector_loader::load_connector
  12: migration_core::migration_engine::MigrationEngine::init
  13: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  14: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  15: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
  16: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  17: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A, B> as futures::future::Future>::poll
  19: futures::task_impl::std::set
  20: <std::thread::local::LocalKey<T>>::with
  21: futures::future::Future::wait
  22: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync
  23: migration_core::rpc_api::RpcApi::handle
  24: migration_engine::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: std::rt::lang_start_internal
  29: main
```

**Comment by pantharshit00** [comment]
Also, postgres is running locally on port 5431

**Comment by mavilein** [comment]
Fixed in: https://github.com/prisma/prisma/commit/9bcad048f26c23f5f23f73c4680cb56be05a4925
This will ship with `preview3`.

**Comment by pantharshit00** [comment]
Fix is also available in the current alpha

**Comment by herbertpimentel** [comment]
@mavilein I still have problem even using  prisma2@2.0.0-alpha.46, binary version: 4f33077038a490e4b2c1c260f109309e4a447181


at first I was trying to using a existing db with tables in different schemas and the I get this error Cannot read property 'fields' of undefined

So I created a entire blank db with only one simple table and then still have the problem "Error in lift engine"

There's some other information I can provide to help identify it ?!

I am running it on macOSX with "PostgreSQL 10.5+tjap-20180921 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit"




^CiMac-de-Herbert:prisma2 herbertpimentel$ psql
-bash: psql: command not found
iMac-de-Herbert:prisma2 herbertpimentel$ prisma2 init app
✔ Connected to database
✔ Connected to database

 Select the schema you want to introspect
 ──────────────────────────────────────────────────

  ◉ public              1 tables, 16.384 KB 

  New schema Or enter a name for a new schema

 ──────────────────────────────────────────────────


❯  Introspect          Error in lift engine: 
❮  Back                (Database credentials)

**Comment by timsuchanek** [comment]
@herbertpimentel thanks a lot for letting is know! Can you turn the env var `DEBUG=*` and report the output in a separate issue? That would help us a lot!

**Comment by timsuchanek** [comment]
Fixed in latest version. We still have this issue in Photon, we track it here https://github.com/prisma/photonjs/issues/156
