### ISSUE TITLE
Lift in preview019 altering columns

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/lift#264]
After I deleted the migration folder, truncated _migrations table and created a fresh migration, lift is altering fields (resets/drops value) that haven't been removed and schema has not changed. Details and reproduction below.

**Comment by Asciant** [comment]
I'm having the same issue, thought I would mention report id 904 (as per the CLI's request).

```
Error in migration engine.
Reason: [src/libcore/result.rs:1165:5] Error parsing the migration steps: Error("missing field `tag`", line: 1, column: 83)
```
I also deleted the migrations folder.

Deleting the SQLite DB and then running Prisma2 dev fixed the issue, I assume it relates to there being DB records associated with a migration, but no physical files?

**Comment by malekjaroslav** [comment]
Might be related: https://github.com/prisma/lift/issues/239

**Comment by malekjaroslav** [comment]
So I don't know it happened but now even if I downloaded to preview 18.2 is still wipes out nullable fields and restarts DataTime fields.

**Comment by tomhoule** [comment]
This should be fixed by https://github.com/prisma/prisma-engine/pull/318 :) It will be in the next alpha release.

**Comment by tomhoule** [comment]
You had a _lot_ of columns with that problem, so the fix may not work for absolutely all of them. Please open an issue if it still doesn't look right in the next alpha (476).

**Comment by malekjaroslav** [comment]
@tomhoule Alpha fixed most issues, but I still have the warning with a Float type that is getting altered

**Comment by malekjaroslav** [comment]
Also @tomhoule if you create a database from the datamodel I posted above and seed it (as above), then running `prisma2 lift save` shows this warning: 

```
⚠️  There might be data loss when applying the migration:

  • You are about to alter the column `length` on the `File` table, which still contains 2 non-null values. The data in that column will be lost.
  • You are about to alter the column `preview` on the `File` table, which still contains 2 non-null values. The data in that column will be lost.
  • You are about to alter the column `password` on the `User` table, which still contains 1 non-null values. The data in that column will be lost.
  • You are about to alter the column `username` on the `User` table, which still contains 1 non-null values. The data in that column will be lost.
```

**Comment by tomhoule** [comment]
Looking into it now

**Comment by tomhoule** [comment]
Weird, the warnings say that the columns are altered but they're not in the schema from the issue description. Can you try narrowing the issue down and opening a new issue? Sorry to ask this much but I don't have tons of time to investigate at the moment.

**Comment by malekjaroslav** [comment]
@tomhoule I put together a more detailed issue, hope it helps https://github.com/prisma/lift/issues/267

**Comment by tomhoule** [comment]
Thanks a lot!
